README:
  - ./README.md

CHANGELOG:
  - ./CHANGELOG.md

pages:
  - any: ["src/pages/**/*"]

templates:
  - any: ["src/templates/**/*"]

action:
  - any: [".github/**/*"]

dependencies:
  - ./yarn.lock
