name: "Labeler"
on: [pull_request]

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@master
        with:
          configuration-path: "./.github/actions/labeler.yml"
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
