name: Blog CI
on:
  push:
    branches: [ prod/deploy ]  # prod/deploy 브랜치에 push 될 경우에 해당 action 을 실행
  pull_request:
    branches:  [ prod/deploy ]

jobs:
  checks:
    if: github.event_name != 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Test Build
        run: |
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          yarn install
          fi
          yarn build
      - name: if fail
        uses: actions/github-script@v4.0.2
        with:
          github-token: ${{github.token}}
          script: |
            const ref = "${{github.ref}}"
            const pull_number = Number(ref.split("/")[2])
            await github.pulls.createReview({
              ...context.repo,
              pull_number,
              body:"빌드에 실패하였습니다 :( 🙏🙏😛",
              event: "REQUEST_CHANGES"
            })
        if: failure()
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Package Installation  
        run: |
          yarn install --frozen-lockfile
      - name: Build
        run: |
          yarn build
      - name: Release to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
