name: Blog Release
on:
  push: # prod/deploy 브랜치에 push 될 경우에 해당 action 을 실행
    branches: [prod/deploy]
  pull_request: # prod/deploy 브랜치에 PR 이 열릴 경우에 해당 action 을 실행
    types: [opened, reopened]
    branches: [prod/deploy]

jobs:
  gh-release:
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"
      - name: Package Installation
        run: |
          yarn install --frozen-lockfile
      - name: Build
        run: |
          yarn build
      - name: Release to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

      - name: Slack Notification on SUCCESS
        if: ${{ success() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: notify-blog-release
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_TITLE: "${{ github.repository }}"
          SLACK_MESSAGE: "Build Success! :rocket:"
          SLACK_USERNAME: RELEASE
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Slack Notification on Failure
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: notify-blog-release
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'green' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_TITLE: "${{ github.repository }}"
          SLACK_MESSAGE: "Build Failed! :rocket:"
          SLACK_USERNAME: RELEASE
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
